development:
  adapter: postgresql
  encoding: unicode
  database: simple_development
  host: localhost
  pool: 5
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: simple_test
  host: localhost
  pool: 5
  min_messages: warning
